name: release

on:
  release:
    types:
      - published

env:
  VERSION: 1.0.0

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore Packages
        run: dotnet restore src/FeatBit.ClientSdk/FeatBit.ClientSdk.csproj

      - name: Build Solution
        run: dotnet build src/FeatBit.ClientSdk/FeatBit.ClientSdk.csproj -c Release --no-restore

      - name: Run Tests
        run: |
          dotnet restore tests/FeatBit.ClientSdk.Tests
          dotnet test -v normal \
              -c Release --no-build \
              tests/FeatBit.ClientSdk.Tests/FeatBit.ClientSdk.Tests.csproj

      - name: Set Version Variable
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Pack FeatBit.ClientSdk
        run: dotnet pack ./src/FeatBit.ClientSdk/FeatBit.ClientSdk.csproj -c Release --no-restore --no-build --output ${VERSION} /p:PackageVersion=$VERSION

      - name: Publish NuGet Package
        run: dotnet nuget push ${VERSION}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate